### ISSUE TITLE
Listener leak in debug session

### ISSUE THREAD

**Issue by spoenemann** [arduino/arduino-pro-ide#183]
```
root WARN Error: Possible Emitter memory leak detected. 123 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.../node_modules/@theia/core/lib/common/event.js.Emitter.checkMaxListeners (http://localhost:3000/bundle.js:55586:26)
    at Emitter._event.Object.assign.maxListeners [as _event] (http://localhost:3000/bundle.js:55553:27)
    at DebugSessionConnection.push.../node_modules/@theia/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.on (http://localhost:3000/30.bundle.js:4256:38)
    at DebugSession.push.../node_modules/@theia/debug/lib/browser/debug-session.js.DebugSession.on (http://localhost:3000/30.bundle.js:5876:32)
    at http://localhost:3000/30.bundle.js:5813:34
    at new Promise (<anonymous>)
    at DebugSession.push.../node_modules/@theia/debug/lib/browser/debug-session.js.DebugSession.exited (http://localhost:3000/30.bundle.js:5812:16)
    at DebugSession.<anonymous> (http://localhost:3000/30.bundle.js:5797:51)
    at step (http://localhost:3000/30.bundle.js:5236:23)
    at Object.next (http://localhost:3000/30.bundle.js:5217:53)
```

**Comment by spoenemann** [comment]
Solved.
